# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
# AvalancheGo version
avalanchego_min_version: 1.9.6
avalanchego_binary_name: "avalanchego-linux-amd64-v{{ avalanchego_version }}.tar.gz"
avalanchego_binary_url: "https://github.com/ava-labs/avalanchego/releases/download/v{{ avalanchego_version }}/{{ avalanchego_binary_name }}"

# AvalancheGo GPG key
avalanchego_gpg_key_name: avalanchego.gpg.key
avalanchego_gpg_key_url: "https://downloads.avax.network/{{ avalanchego_gpg_key_name }}"

# Install directories
avalanchego_releases_dir: "{{ avalanchego_install_dir }}/releases"
avalanchego_current_dir: "{{ avalanchego_install_dir }}/current"
avalanchego_plugins_dir: "{{ avalanchego_current_dir }}/plugins"

# Configuration directories
avalanchego_subnets_conf_dir: "{{ avalanchego_conf_dir }}/subnets"
avalanchego_chains_conf_dir: "{{ avalanchego_conf_dir }}/chains"
avalanchego_vms_conf_dir: "{{ avalanchego_conf_dir }}/vms"

# HTTP URLs protocol
avalanchego_http_protocol: "{{ 'https' if avalanchego_https_enabled else 'http' }}"

# String templates for VM files to download
avalanchego_vm_binary_filename: "{{ vm_name }}_{{ vm_version }}_linux_amd64.tar.gz"
avalanchego_vm_checksum_filename: "{{ vm_name }}_{{ vm_version }}_checksums.txt"

# Avalanche constants
avalanche_primary_network_id: 11111111111111111111111111111111LpoYY

# List of VMs supported by the collection
avalanchego_vms_list:
  subnet-evm:
    download_url: https://github.com/ava-labs/subnet-evm/releases/download
    id: spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
    # Used in Ash CLI
    ash_vm_type: SubnetEVM
    aliases:
      - subnet-evm
    versions_comp:
      0.4.8:
        ge: 1.9.6
        le: 1.9.8
      0.4.9:
        ge: 1.9.9
        le: 1.9.9
      0.4.10:
        ge: 1.9.9
        le: 1.9.9
      0.4.11:
        ge: 1.9.10
        le: 1.9.16
      0.4.12:
        ge: 1.9.10
        le: 1.9.16
      0.5.0:
        ge: 1.10.0
        le: 1.10.0
      0.5.1:
        ge: 1.10.1
        le: 1.10.3
      0.5.2:
        ge: 1.10.1
        le: 1.10.3
