# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
# AvalancheGo version
avalanchego_min_version: 1.10.0
avalanchego_gh_repo: ava-labs/avalanchego
avalanchego_binary_arch: amd64
avalanchego_binary_name: "avalanchego-linux-{{ avalanchego_binary_arch }}-v{{ avalanchego_version }}.tar.gz"
avalanchego_binary_url: "https://github.com/{{ avalanchego_gh_repo }}/releases/download/v{{ avalanchego_version }}/{{ avalanchego_binary_name }}"

# AvalancheGo GPG key
avalanchego_gpg_key_name: avalanchego.gpg.key
avalanchego_gpg_key_url: "https://downloads.avax.network/{{ avalanchego_gpg_key_name }}"

# Install directories
avalanchego_releases_dir: "{{ avalanchego_install_dir }}/releases"
avalanchego_current_dir: "{{ avalanchego_install_dir }}/current"
avalanchego_plugins_dir: "{{ avalanchego_current_dir }}/plugins"

# Configuration directories
avalanchego_subnets_conf_dir: "{{ avalanchego_conf_dir }}/subnets"
avalanchego_chains_conf_dir: "{{ avalanchego_conf_dir }}/chains"
avalanchego_vms_conf_dir: "{{ avalanchego_conf_dir }}/vms"

# HTTP URLs protocol
avalanchego_http_protocol: "{{ 'https' if avalanchego_https_enabled else 'http' }}"

# String templates for VM files to download
avalanchego_vm_binary_arch: amd64
avalanchego_vm_binary_filename: "{{ vm_info.binary_filename }}_{{ vm_version }}_linux_{{ avalanchego_vm_binary_arch }}.tar.gz"
avalanchego_vm_checksum_filename: "{{ vm_info.binary_filename }}_{{ vm_version }}_checksums.txt"

# Avalanche constants
avalanche_primary_network_id: 11111111111111111111111111111111LpoYY

# List of VMs supported by the collection
avalanchego_vms_list:
  subnet-evm:
    download_url: https://github.com/ava-labs/subnet-evm/releases/download
    id: srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy
    # Used in Ash CLI
    ash_vm_type: SubnetEVM
    # The VM binary filename
    binary_filename: subnet-evm
    # Only one of `version_comp_repo` or `version_comp_static`
    # The GitHub repository where to find the `compatibility.json` file
    version_comp_gh_repo: ava-labs/subnet-evm
    # The static compatibility matrix
    # Example:
    # versions_comp_static:
    #   0.5.0:
    #     ge: 1.10.0
    #     le: 1.10.0
