# SPDX-License-Identifier:  BUSL-1.1
# Copyright (c) 2022-2023, E36 Knots
---
- name: Configure Blockscout Docker
  include_tasks: config-blockscout.yml

- name: Start Blockscout Docker
  include_tasks: start-blockscout.yml
