# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
collections:
  - name: prometheus.prometheus
    version: 0.23.0
  - name: grafana.grafana
    version: 5.7.0

roles:
  - name: geerlingguy.docker
    version: 6.1.0
