# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
collections:
  - name: prometheus.prometheus
    version: 0.4.0

roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: cloudalchemy.grafana
    version: 0.18.0
