# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
collections:
  - name: prometheus.prometheus
    version: 0.30.0
  - name: grafana.grafana
    version: 6.0.6

roles:
  - name: geerlingguy.docker
    version: 7.9.0
