---
- name: Launch Graph Node container
  community.docker.docker_container:
    name: graph-node
    image: "graphprotocol/graph-node:{{ graph_node.version }}"
    restart_policy: always
    network_mode: host
    env:
      postgres_host: 127.0.0.1
      postgres_port: "{{ graph_node.postgres.port }}"
      postgres_user: "{{ graph_node.postgres.user }}"
      postgres_pass: "{{ graph_node.postgres.password }}"
      postgres_db:   "{{ graph_node.postgres.db }}"
      ipfs:          "127.0.0.1:{{ graph_node.ipfs.port }}"
      ethereum:      "{{ graph_node.ethereum.network }}:{{ graph_node.ethereum.rpc_url }}"
      GRAPH_LOG:     info
    docker_host: unix:///var/run/docker.sock

- name: Restart Graph Node container (if needed)
  meta: flush_handlers
