---
- name: Configure Graph Node directories
  import_tasks: configure-graph-node.yml

- name: Check if the Graph Node container is present
  command: docker ps -q --filter "name=graph-node"
  register: graph_node_container
  changed_when: false

- name: Start Graph Node service
  import_tasks: start-graph-node.yml
