---
- name: Configure Graph Node directories
  import_tasks: configure-graph-node.yml

- name: Re/start Graph Node Docker if needed
  meta: flush_handlers

- name: Start Graph Node service
  import_tasks: start-graph-node.yml
