version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:v1.23.3
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      - /etc/blockscout/conf/vars-frontend.env
