version: '3.9'

services:
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:v1.10.0
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  /etc/blockscout/conf/vars-smart-contract-verifier.env
