version: '3.9'

services:
  stats:
    image: ghcr.io/blockscout/stats:v2.11.1
    build: .
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'stats'
    env_file:
      - /etc/blockscout/conf/vars-stats.env
