version: '3.9'

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'visualizer'
    env_file:
      - /etc/blockscout/conf/vars-visualizer.env
