# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Create Marketplace config
  set_fact:
    blockscout_frontend_env_variables: 
      NEXT_PUBLIC_MARKETPLACE_ENABLED: 'true'
      NEXT_PUBLIC_MARKETPLACE_CONFIG_URL: "{{ blockscout_assets_url }}/marketplace-config.json"
      NEXT_PUBLIC_MARKETPLACE_SUBMIT_FORM: https://forms.gle/S7LK7M6QiNeFnGUN8
  when: blockscout_marketplace_app_list | length > 0

- name: Create Blockscout directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  loop:
    - "{{ blockscout_conf_dir }}"
    - "{{ blockscout_custom_dir }}"
    - "{{ blockscout_log_dir }}"
    - "{{ blockscout_data_dir }}"
    - "{{ blockscout_assets_dir }}"
  tags: assets-sync

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ blockscout_conf_dir }}/docker-compose.yml"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Upload services
  copy:
    src: "services"
    dest: "{{ blockscout_custom_dir }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Ensure proxy directory exists
  file:
    path: "{{ blockscout_custom_dir }}/proxy"
    state: directory
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
    mode: '0755'

- name: Template proxy default.conf.template
  template:
    src: default.conf.template.j2
    dest: "{{ blockscout_custom_dir }}/proxy/default.conf.template"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-backend.env
  template:
    src: vars-backend.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-backend.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-frontend.env
  template:
    src: vars-frontend.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-frontend.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-visualizer.env
  template:
    src: vars-visualizer.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-visualizer.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_VISUALIZE_SOL2UML_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Template vars-smart-contract-verifier.env
  template:
    src: vars-smart-contract-verifier.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-smart-contract-verifier.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_SC_VERIFIER_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Template vars-sig-provider.env
  template:
    src: vars-sig-provider.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-sig-provider.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_SIG_PROVIDER_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Template vars-stats.env
  template:
    src: vars-stats.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-stats.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_stats_enabled in ['true', true]
  notify: Restart blockscout

- name: Download chart config for stats service
  get_url:
    url: https://raw.githubusercontent.com/blockscout/blockscout-rs/refs/tags/stats/v2.11.1/stats/config/blockscout_instance/{{ item }}
    dest: "{{ blockscout_conf_dir }}/{{ item }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_stats_enabled in ['true', true]
  notify: Restart blockscout
  loop:
    - charts.json
    - layout.json
    - update_groups.json

- name: Customize chart unit
  ansible.builtin.replace:
    path: "{{ blockscout_conf_dir }}/charts.json"
    regexp: "ETH"
    replace: "{{ blockscout_frontend_env_variables.NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL }}"
  when: blockscout_stats_enabled in ['true', true]

- name: Customize chart min unit
  ansible.builtin.replace:
    path: "{{ blockscout_conf_dir }}/charts.json"
    regexp: "Gwei"
    replace: "{{ CURRENCY_MIN_SYMBOL }}"
  when: blockscout_stats_enabled in ['true', true] and CURRENCY_MIN_SYMBOL is defined

- name: Ensure images directory exists
  file:
    path: "{{ blockscout_custom_dir }}/images"
    state: directory
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
    mode: '0755'

- name: Upload logo image
  copy:
    src: "{{ blockscout_header_logo_file }}"
    dest: "{{ blockscout_custom_dir }}/images/{{ blockscout_header_logo_file | basename }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template blockscout.service file
  template:
    src: blockscout.service.j2
    dest: /etc/systemd/system/blockscout.service
  notify: Restart blockscout

- name: Create marketplace-config.json asset
  copy:
    content: "{{ blockscout_marketplace_app_list }}"
    dest: "{{ blockscout_assets_dir }}/marketplace-config.json"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
    mode: '0755'
  when: blockscout_marketplace_app_list | length > 0
  notify: Restart blockscout
  tags: marketplace-sync

- name: Convert NEXT_PUBLIC_FEATURED_NETWORKS to json formatting
  set_fact:
    blockscout_frontend_env_variables:
      NEXT_PUBLIC_FEATURED_NETWORKS: "{{ blockscout_frontend_env_variables.NEXT_PUBLIC_FEATURED_NETWORKS | to_json }}"
  when: "'NEXT_PUBLIC_FEATURED_NETWORKS' in blockscout_frontend_env_variables"

- name: Convert NEXT_PUBLIC_FOOTER_LINKS to json formatting
  set_fact:
    blockscout_frontend_env_variables:
      NEXT_PUBLIC_FOOTER_LINKS: "{{ blockscout_frontend_env_variables.NEXT_PUBLIC_FOOTER_LINKS | to_json }}"
  when: "'NEXT_PUBLIC_FOOTER_LINKS' in blockscout_frontend_env_variables"

- name: Copy assets to expose it through NGINX '/shared' api path
  copy:
    src: "{{ blockscout_extra_assets_dir if blockscout_extra_assets_dir.endswith('/') else blockscout_extra_assets_dir + '/' }}"
    dest: "{{ blockscout_assets_dir }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_extra_assets_dir | length > 0
  notify: Restart blockscout
  tags: assets-sync

- name: Reload systemctl daemons
  systemd:
    daemon_reload: true


