# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Create Blockscout directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  loop:
    - "{{ blockscout_conf_dir }}"
    - "{{ blockscout_custom_dir }}"
    - "{{ blockscout_log_dir }}"
    - "{{ blockscout_data_dir }}"

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ blockscout_conf_dir }}/docker-compose.yml"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Upload services
  copy:
    src: "services"
    dest: "{{ blockscout_custom_dir }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template proxy microservices.conf.template
  template:
    src: microservices.conf.template.j2
    dest: "{{ blockscout_custom_dir }}/proxy/microservices.conf.template"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template proxy default.conf.template
  template:
    src: default.conf.template.j2
    dest: "{{ blockscout_custom_dir }}/proxy/default.conf.template"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-backend.env
  template:
    src: vars-backend.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-backend.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-frontend.env
  template:
    src: vars-frontend.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-frontend.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template vars-visualizer.env
  template:
    src: vars-visualizer.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-visualizer.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_VISUALIZE_SOL2UML_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Template vars-smart-contract-verifier.env
  template:
    src: vars-smart-contract-verifier.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-smart-contract-verifier.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_SC_VERIFIER_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Template vars-sig-provider.env
  template:
    src: vars-sig-provider.env.j2
    dest: "{{ blockscout_conf_dir }}/vars-sig-provider.env"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  when: blockscout_backend_env_vars.MICROSERVICE_SIG_PROVIDER_ENABLED in ['true', true]
  notify: Restart blockscout

- name: Ensure images directory exists
  file:
    path: "{{ blockscout_custom_dir }}/images"
    state: directory
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
    mode: '0755'

- name: Upload logo image
  copy:
    src: "{{ blockscout_header_logo_file }}"
    dest: "{{ blockscout_custom_dir }}/images/{{ blockscout_header_logo_file | basename }}"
    owner: "{{ blockscout_user }}"
    group: "{{ blockscout_user }}"
  notify: Restart blockscout

- name: Template blockscout.service file
  template:
    src: blockscout.service.j2
    dest: /etc/systemd/system/blockscout.service
  notify: Restart blockscout

- name: Reload systemctl daemons
  systemd:
    daemon_reload: true
