# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Configure Blockscout Docker
  include_tasks: config-blockscout.yml

- name: Restart Blockscout Docker if needed
  meta: flush_handlers
  tags:
    - Restart
    - blockscout
    - Restart-blockscout

- name: Start Blockscout Docker
  include_tasks: start-blockscout.yml
