# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Configure Blockscout Docker
  import_tasks: config-blockscout.yml
  tags:
    - config
    - blockscout
    - config-blockscout

- name: Restart Blockscout Docker if needed
  meta: flush_handlers

- name: Start Blockscout Docker
  include_tasks: start-blockscout.yml
  tags:
    - start
    - blockscout
    - start-blockscout
