{
 "title": "eRPC Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P95 resp. time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, network, upstream)) > 0",
     "legendFormat": "{{upstream}} / {{network}}"
    }
   ]
  },
  { "title": "Network-wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network-level Requests",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_request_received_total[30s])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level RPS",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_received_total[30s])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network self-imposed Rate-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_self_rate_limited_total[30s])) by (project, network)",
     "legendFormat": "{{project}}, {{network}}"
    }
   ]
  },
  {
   "title": "Network-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, project, network, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, project, network, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket[5m])) by (le, project, network, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Errors",
   "type": "timeseries",
   "description": "When a request fails even after trying all upstreams and retries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_failed_request_total[30s])) by (project,network,error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{error}}"
    }
   ]
  },
  {
   "title": "Network-level Multiplexed requests",
   "type": "timeseries",
   "description": "When identical requests arrive at the same time they'll be merged, this number shows number of these requests",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_multiplexed_request_total[30s])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Hedged requests",
   "type": "timeseries",
   "description": "Total identical requests that are initiated towards a new upstream while the previous upstream is slow to respond",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_hedged_request_total[30s])) by (project, network, upstream) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Effective hedged requests",
   "type": "timeseries",
   "description": "Total hedged requests that ended up being actually faster and useful. The higher the better. If this value is too low try increasing the failsafe.hedge.quantile to higher value e.g. 0.99",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(increase(erpc_network_hedge_discards_total{attempt!=\"1\"}[30s])) by (project, network, upstream)) / (sum(increase(erpc_network_hedged_request_total{}[30s])) by (project, network, upstream))) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  { "title": "Upstream-wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Upstream-level requests",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_total[30s])) by (project, network, upstream, attempt)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Upstream-level RPS",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_total[30s])) by (project, network, upstream, attempt)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "avg(erpc_upstream_score_overall{network=\"*\"}) by (project, upstream, network)",
     "legendFormat": "{{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level Remote rate-limited Requests",
   "type": "timeseries",
   "description": "Total requests that are sent to upstream but is rate-limited by the provider node",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_remote_rate_limited_total[30s])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level self-imposed Ratel-limited requests",
   "type": "timeseries",
   "description": "Total requests rate-limited locally on eRPC before actually sending, based on defined budget",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_self_rate_limited_total[30s])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Rate-limit budget MaxCount",
   "type": "timeseries",
   "description": "Dynamically tuned value for maxCount of different rate limit budgets",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (budget, method) (erpc_rate_limiter_budget_max_count)\n",
     "legendFormat": "{{budget}}, {{method}}"
    }
   ]
  },
  {
   "title": "Upstream-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, project, upstream))",
     "legendFormat": "p50: {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, project, upstream))",
     "legendFormat": "p95: {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, project, upstream))",
     "legendFormat": "p99: {{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Method resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level warning errors",
   "type": "timeseries",
   "description": "The failures are more tolerable (e.g. rate limited, hedge-cancellations, etc) which doesn't mean upstream is failing, therefore less alert-worthy",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"warning\"}[30s])) by (project, network, upstream, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level critical errors",
   "type": "timeseries",
   "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"critical\"}[30s])) by (project, network, upstream, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Cache SET success total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_success_total[30s])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET success duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_success_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_set_success_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_error_total[30s])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_error_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_set_error_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_hit_total[30s])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_miss_total[30s])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_error_total[30s])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  }
 ]
}