{
 "title": "Network",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime average",
   "type": "timeseries",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_weighted_average{job=\"avalanchego\"}",
     "legendFormat": "Uptime average {{node_id}}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "timeseries",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_rewarding_stake{job=\"avalanchego\"}",
     "legendFormat": "Rewarding stake {{node_id}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "description": "Number of network peers the node is connected to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_network_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers connected {{node_id}}"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "timeseries",
   "description": "Shows the amount of time this node will wait for a response to a request before considering the request failed, and the average time it takes to get a response to a request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avalanche_requests_current_timeout{job=\"avalanchego\"}",
     "legendFormat": "Timeout {{node_id}}"
    },
    {
     "expr": "avalanche_requests_average_latency{job=\"avalanchego\"}",
     "legendFormat": "Response Time {{node_id}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of outstanding requests related to consensus/bootstrapping. Doesn't include handshake messages.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avalanche_requests_outstanding{job=\"avalanchego\"}",
     "legendFormat": "Outstanding Requests {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs{io=\"received\", job=\"avalanchego\"}[1m])",
     "legendFormat": "{{ op }} compressed={{ compressed }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs{io=\"sent\", job=\"avalanchego\"}[1m])",
     "legendFormat": "{{ op }} compressed={{ compressed }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs_bytes{io=\"received\", job=\"avalanchego\"}[1m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Sent Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs_bytes{io=\"sent\", job=\"avalanchego\"}[1m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Received Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "type": "math", "expression": "$A / $B" }
   ]
  },
  {
   "title": "Average Sent Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "type": "math", "expression": "$A / $B" }
   ]
  },
  {
   "title": "Queries Sent per Accepted Container",
   "type": "timeseries",
   "description": "Considers the X-Chain, P-Chain and C-Chain. A lower value indicates vote pipelining (good.) A higher value indicates failed polls (not good.)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "targets": [
    { "type": "math", "expression": "$A / $B" }
   ]
  },
  {
   "title": "Messages Awaiting Send",
   "type": "timeseries",
   "description": "Number of messages that are queued to be sent to peers",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_awaiting_release{job=\"avalanchego\"}",
     "legendFormat": "Messages {{node_id}}"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "timeseries",
   "description": "Amount of the stake in AVAX that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_benchlist_benched_weight/1000000000",
     "legendFormat": "{{ chain }} {{node_id}}"
    }
   ]
  },
  { "title": "Inbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Inbound Byte Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_validator_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire bytes from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_byte_throttler_inbound_acquire_latency_sum{job=\"avalanchego\"}[2m])/increase(avalanche_network_byte_throttler_inbound_acquire_latency_count{job=\"avalanchego\"}[2m])",
     "legendFormat": "Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_buffer_throttler_inbound_acquire_latency_sum{job=\"avalanchego\"}[2m])/increase(avalanche_network_buffer_throttler_inbound_acquire_latency_count{job=\"avalanchego\"}[2m])",
     "legendFormat": "Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Awaiting Release (Messages Processing)",
   "type": "timeseries",
   "description": "Number of messages that are currently being handled and haven't yet returned their bytes to the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_release{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Release {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire from the inbound message buffer throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "avalanche_network_buffer_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_at_large_bytes{job=\"avalanchego\"}",
     "legendFormat": "Remaining Bytes {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound bandwidth throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "avalanche_network_bandwidth_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Acquire {{node_id}}"
    }
   ]
  },
  { "title": "Outbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Outbound Throttler Remaining At-Large Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_at_large_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  {
   "title": "Outbound Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_validator_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Messages Failed To Send per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs_failed_to_send{job=\"avalanchego\"}[1m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Failed To Parse per Minute",
   "type": "timeseries",
   "description": "Number of messages that could not be parsed because they were of unknown type or invalidly formatted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "increase(avalanche_network_msgs_failed_to_parse[1m])",
     "legendFormat": "Failed to Parse {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of inbound messages dropped (not processed) due to expiration in last minute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(avalanche_handler_expired[1m]) or 0 * up)",
     "legendFormat": "Messages Dropped {{node_id}}"
    }
   ]
  },
  {
   "title": "Outbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of outbound messages dropped (not sent) due to rate-limiting in the last minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "increase(avalanche_network_throttler_outbound_acquire_failures{job=\"avalanchego\"}[1m])",
     "legendFormat": "Messages Dropped {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connections Dropped due to Rate-Limiting per Minute",
   "type": "timeseries",
   "description": "Number of inbound connections dropped due to inbound connection rate-limiting",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "increase(avalanche_network_inbound_conn_throttler_rate_limited{job=\"avalanchego\"}[1m])",
     "legendFormat": "Rate-Limited {{node_id}}"
    }
   ]
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Average Message Compression Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_codec_compressed_duration{direction=\"compression\"}[5m])/increase(avalanche_network_codec_compressed_count{direction=\"compression\"}[5m])",
     "legendFormat": "{{ op }} {{ type }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Message Decompression Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_codec_compressed_duration{direction=\"decompression\"}[5m])/increase(avalanche_network_codec_compressed_count{direction=\"decompression\"}[5m])",
     "legendFormat": "{{ op }} {{ type }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Bytes Saved by Compression",
   "type": "timeseries",
   "description": "Rate at which we save bytes (don't send/receive them over the network) by compressing messages/receiving compressed messages.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_msgs_bytes_saved[5m])",
     "legendFormat": "{{ io }} {{ op }} {{node_id}}"
    }
   ]
  }
 ]
}