# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Create the blockchains
  include_tasks: create-blockchain.yml
  vars:
    subnet_id: "{{ subnet_create_res.output.id }}"
  loop: "{{ subnet_blockchains_list }}"
  loop_control:
    loop_var: blockchain
    label: "{{ blockchain.name }}"
