# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Create Ash CLI directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ash_cli_owner }}"
    group: "{{ ash_cli_group }}"
  loop:
    - "{{ ash_cli_releases_dir }}"
    - "{{ ash_cli_bin_dir }}/ash-{{ ash_cli_version }}"
    - "{{ ash_cli_conf_dir }}"

- name: Set ash_cli_binary_arch according to ansible_architecture
  set_fact:
    ash_cli_binary_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ash_cli_binary_arch }}"

- name: "Download Ash CLI {{ ash_cli_version }} binary"
  get_url:
    url: "{{ ash_cli_binary_url }}"
    dest: "{{ ash_cli_releases_dir }}/{{ ash_cli_binary_name }}"
    checksum: "sha512:{{ ash_cli_binary_url }}.sha512"
    owner: "{{ ash_cli_owner }}"
    group: "{{ ash_cli_group }}"

- name: "Unpack Ash CLI {{ ash_cli_version }} binary"
  unarchive:
    src: "{{ ash_cli_releases_dir }}/{{ ash_cli_binary_name }}"
    dest: "{{ ash_cli_bin_dir }}/ash-{{ ash_cli_version }}"
    remote_src: true
    owner: "{{ ash_cli_owner }}"
    group: "{{ ash_cli_group }}"
    mode: 0755
    creates: "{{ ash_cli_bin_dir }}/ash-{{ ash_cli_version }}/ash"

- name: "Create the symlink to Ash CLI {{ ash_cli_version }} binary"
  file:
    src: "{{ ash_cli_bin_dir }}/ash-{{ ash_cli_version }}/ash"
    dest: "{{ ash_cli_bin_dir }}/ash"
    state: link
    owner: "{{ ash_cli_owner }}"
    group: "{{ ash_cli_group }}"

- name: Template ash command
  template:
    src: ash-command.j2
    dest: /usr/local/bin/ash
    owner: "{{ ash_cli_owner }}"
    group: "{{ ash_cli_group }}"
    mode: 0755
