# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
## /!\ Cannot be used on mainnet /!\
# Parameters
# - subnet_id: ID of the Subnet to add the validator to

- name: Check that Ash CLI is installed
  shell: ash help
  changed_when: false

- name: Get node information
  ash.avalanche.ash_cmd:
    command: avalanche node info
    options:
      http-host: "{{ avalanchego_http_host }}"
      http-port: "{{ avalanchego_http_port }}"
      https: "{{ avalanchego_https_enabled }}"
  register: node_info_res

- name: Add the node as validator
  include_role:
    name: ash.avalanche.subnet
    tasks_from: add-validator
  vars:
    subnet_avalanche_network_id: "{{ avalanchego_network_id }}"
    node_id: "{{ node_info_res.output.id }}"
    subnet_txs_private_key: "{{ validator_txs_private_key }}"
    subnet_txs_key_encoding: "{{ validator_txs_key_encoding }}"
    start_time_command: "{{ validator_start_time_command }}"
    start_time: "{{ validator_start_time }}"
    end_time_command: "{{ validator_end_time_command }}"
    end_time: "{{ validator_end_time }}"
    stake_or_weight: "{{ validator_stake_or_weight }}"
    delegation_fee: "{{ validator_delegation_fee }}"
