# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: "Get symlinks in {{ avalanchego_plugins_dir }}"
  find:
    paths: "{{ avalanchego_plugins_dir }}"
    file_type: link
  register: links

- name: Set expected_plugins variable
  set_fact:
    expected_plugins: "{{ expected_plugins | default([]) + [avalanchego_vms_list[item].id] }}"
  loop: "{{ avalanchego_vms_install.keys() }}"

- name: "Remove outdated links in {{ avalanchego_plugins_dir }}"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in expected_plugins
  loop: "{{ links.files }}"
  loop_control:
    label: "{{ item.path }}"
