# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Create chains conf directories
  file:
    path: "{{ avalanchego_chains_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_group }}"
  loop: "{{ avalanchego_chains_configs.keys() }}"

- name: Generate chains config.json
  copy:
    content: "{{ item.value | to_nice_json }}\n"
    dest: "{{ avalanchego_chains_conf_dir }}/{{ item.key }}/config.json"
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_group }}"
  loop: "{{ avalanchego_chains_configs | dict2items }}"
  notify: Restart avalanchego
