# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Generate subnets JSON config files
  copy:
    content: "{{ item.value | to_nice_json }}\n"
    dest: "{{ avalanchego_subnets_conf_dir }}/{{ item.key }}.json"
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_group }}"
  loop: "{{ avalanchego_subnets_configs | dict2items }}"
  notify: Restart avalanchego
