# Copyright (C) 2022, Léo Schoukroun
# See the file LICENSE for licensing terms.
---
- name: Add validator playbook
  hosts: avalanche_nodes
  tasks:
    - name: Add validator task
      include_role:
        name: ash.avalanche.node
        tasks_from: add-validator.yml
