# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
# This playbook is provided as an example of how to create a blockchain in an existing subnet.
# The create_subnet.yml playbook is the recommended way to create a subnet and its blockchains.
- name: Create the blockchain
  hosts: subnet_txs_host
  tasks:
    - include_role:
        name: ash.avalanche.subnet
        tasks_from: create-blockchain
      vars:
        subnet_id: 2MLKdrcEx4nfKZS9dR7fbUVja7NwtSRjHcn5yFjJThxnYTYW6Q
        blockchain:
          name: AdditionalBlockchain
          vm: subnet-evm
          genesis_data:
            config:
              chainId: 77777
              homesteadBlock: 0
              eip150Block: 0
              eip150Hash: "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0"
              eip155Block: 0
              eip158Block: 0
              byzantiumBlock: 0
              constantinopleBlock: 0
              petersburgBlock: 0
              istanbulBlock: 0
              muirGlacierBlock: 0
              subnetEVMTimestamp: 0
              feeConfig:
                gasLimit: 8000000
                minBaseFee: 25000000000
                targetGas: 15000000
                baseFeeChangeDenominator: 36
                minBlockGasCost: 0
                maxBlockGasCost: 1000000
                targetBlockRate: 2
                blockGasCostStep: 200000
            alloc:
              8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC:
                balance: "0x295BE96E64066972000000"
            nonce: "0x0"
            timestamp: "0x0"
            extraData: "0x00"
            gasLimit: "0x7A1200"
            difficulty: "0x0"
            mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
            coinbase: "0x0000000000000000000000000000000000000000"
            number: "0x0"
            gasUsed: "0x0"
            parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
