# Copyright (C) 2022, Léo Schoukroun
# See the file LICENSE for licensing terms.
---
- name: Create admin user playbook
  hosts: avalanche_nodes
  tasks:
    - name: Create admin user task
      include_role:
        name: ash.avalanche.node
        tasks_from: admin-user.yml
