# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Declare graph_nodes group and frontend host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add frontend to graph_nodes group
      add_host:
        name: frontend
        groups: graph_nodes
      run_once: true

- name: Deploy Graph Node stack
  hosts: graph_nodes
  become: true
  pre_tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: true

  roles:
    - role: geerlingguy.docker
    - role: ash.avalanche.graph_node
