# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Install Blockscout
  hosts: blockscout
  become: true
  roles:
    - role: geerlingguy.docker
      tags: 
        - install
        - blockscout
        - install-blockscout
    - role: ash.avalanche.evm.blockscout
