# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Install Avalanche Faucet
  hosts: faucet
  become: true
  roles:
    - role: geerlingguy.docker
    - role: ash.avalanche.faucet
