# SPDX-License-Identifier:  BUSL-1.1
# Copyright (c) 2022-2023, E36 Knots
---
- name: Install Prometheus Node Exporter
  hosts: avalanche_nodes
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter

- name: Install Prometheus
  hosts: prometheus
  become: true
  roles:
    - role: prometheus.prometheus.prometheus

- name: Install Grafana
  hosts: grafana
  become: true
  roles:
    - role: cloudalchemy.grafana

- name: Import templated Grafana dashboard
  hosts: grafana
  become: true
  tasks:
    - name: Template subnets Grafana dashboard
      template:
        src: "{{ item }}"
        dest: "{{ grafana_data_dir }}/dashboards/{{ item | basename | regex_replace('\\.j2$', '') }}"
        owner: grafana
        group: grafana
        mode: 0640
      loop:
        - "{{ playbook_dir }}/../files/dashboards/subnets.json.j2"
      when: grafana_subnets_dashboard_variables is defined
      register: template_subnets

    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
      when: template_subnets.changed
