# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
# Blockscout version
blockscout_image: blockscout/blockscout
blockscout_image_version: 6.1.0

# Configuration directories
blockscout_conf_dir: /etc/blockscout/conf
blockscout_custom_dir: "{{ blockscout_conf_dir }}/custom"

# Log directory
blockscout_log_dir: /var/log/blockscout

# Data directory
blockscout_data_dir: /var/lib/postgres

# User
blockscout_user: root

# Blockscout variables
blockscout_rpc: http://10.238.106.22:9650/ext/bc/RfX8YRUHePxFENBZFwaNt1tP6CR6RQ4hJJ5AqYv49LRoSKniK/rpc
blockscout_header_logo_file: ash-logo-circle-30.svg

# Blockscout env variables
# --> https://docs.blockscout.com/for-developers/information-and-settings/env-variables
blockscout_backend_env_vars:
# Rpc the client is using
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_HTTP_URL: "{{ blockscout_rpc }}"
  ETHEREUM_JSONRPC_TRACE_URL: "{{ blockscout_rpc }}"

  # Postgres database endpoint
  DATABASE_URL: postgresql://postgres:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
  SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN

  # Network
  NETWORK: EVM
  SUBNETWORK: MySubnet

  # Port
  PORT: 4000

  # Chain Id
  CHAIN_ID: 66666

  # Logo
  LOGO: "/images/{{ blockscout_header_logo_file }}"

  # Footer
  FOOTER_LOGO: "/images/{{ blockscout_header_logo_file }}"
  FOOTER_GITHUB_LINK: "https://github.com/AshAvalanche"
  FOOTER_CHAT_LINK: "https://discord.gg/r82w73jS"

  # Enable SSL encryption for ecto queries
  ECTO_USE_SSL: "false"

  # Fetching coin exchange rates from CoinGecko
  DISABLE_EXCHANGE_RATES: "true"

  # List of supported chains for chain dropdown
  SUPPORTED_CHAINS: []

  # Number of days for fetching of history of txs count for display
  TXS_STATS_DAYS_TO_COMPILE_AT_INIT: 10

blockscout_frontend_env_variables:
  NEXT_PUBLIC_API_HOST: 10.238.106.47
  NEXT_PUBLIC_API_PROTOCOL: http
  # NEXT_PUBLIC_STATS_API_HOST: http://10.238.106.212:8080
  NEXT_PUBLIC_NETWORK_NAME: Ash Subnet
  NEXT_PUBLIC_NETWORK_SHORT_NAME: Ash
  NEXT_PUBLIC_NETWORK_ID: 66666
  NEXT_PUBLIC_NETWORK_CURRENCY_NAME: AshCoin
  NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ASH
  NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18
  NEXT_PUBLIC_API_BASE_PATH: /
  NEXT_PUBLIC_APP_HOST: 10.238.106.47
  NEXT_PUBLIC_APP_PROTOCOL: http
  NEXT_PUBLIC_HOMEPAGE_CHARTS: ['daily_txs']
  NEXT_PUBLIC_VISUALIZE_API_HOST: http://10.238.106.47:8081
  NEXT_PUBLIC_IS_TESTNET: "true"
  NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
  NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml

blockscout_visualizer_env_variables:
  VISUALIZER__SERVER__GRPC__ENABLED: "false"
