# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---

# Auto-restart
## The restart is triggered by any version or configuration change
blockscout_auto_restart: true

# Configuration directories
blockscout_conf_dir: /etc/blockscout/conf
blockscout_custom_dir: "{{ blockscout_conf_dir }}/custom"
blockscout_assets_dir: "{{ blockscout_custom_dir }}/shared"

# Log directory
blockscout_log_dir: /var/log/blockscout

# Data directory
blockscout_data_dir: /var/lib/postgres

# User
blockscout_user: root

# Blockscout variables
blockscout_rpc: http://10.238.106.22:9650/ext/bc/RfX8YRUHePxFENBZFwaNt1tP6CR6RQ4hJJ5AqYv49LRoSKniK/rpc
blockscout_header_logo_file: ash-logo-circle-30.svg

# Frontend
blockscout_frontend_ip: "10.238.106.149"
blockscout_frontend_protocol: http
blockscout_frontend_websocket_protocol: ws
blockscout_frontend_host_name: "{{ blockscout_frontend_ip }}"
blockscout_frontend_url: "{{ blockscout_frontend_protocol }}://{{ blockscout_frontend_host_name }}"
blockscout_assets_url: "{{ blockscout_frontend_url }}/shared"
blockscout_extra_assets_dir: '' ## eg. A folder containing logo, icon, etc.

# Services
# Stats
blockscout_stats_enabled: "false"

# Marketplace (https://github.com/blockscout/docs/blob/master/setup/env-variables/frontend-common-envs/envs.md#marketplace-app-configuration-properties)
# Required fields: blockscout_marketplace_app_list: [{id: 'app', title: 'The App', logo: 'app-logo.png', shortDescription: 'Awesome app', categories: ['Security', 'Tools'], author: 'Bob', url: 'http://app.com', description: 'This is an awesome app']}]
blockscout_marketplace_app_list: []

# CURRENCY_MIN_SYMBOL: nASH

# Blockscout env variables
# --> https://docs.blockscout.com/for-developers/information-and-settings/env-variables
blockscout_backend_env_vars:
  # Rpc the client is using
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_HTTP_URL: "{{ blockscout_rpc }}"
  ETHEREUM_JSONRPC_TRACE_URL: "{{ blockscout_rpc }}"

  # Postgres database endpoint
  DATABASE_URL: postgresql://postgres:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
  SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN

  # Network
  NETWORK: EVM
  SUBNETWORK: MySubnet

  # Port
  PORT: 4000

  # Indexer
  INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "false" # It uses txpool_content which is some times disabled on nodes
  INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "false" # It uses debug_traceTransaction which is some times disabled on nodes

  # Logo
  LOGO: /app/apps/block_scout_web/assets/static/images/{{ blockscout_header_logo_file | basename }}

  # Footer
  FOOTER_LOGO: /app/apps/block_scout_web/assets/static/images/{{ blockscout_header_logo_file | basename }}

  FAVICON_MASTER_URL: /app/apps/block_scout_web/assets/static/images/{{ blockscout_header_logo_file | basename }}

  # Enable SSL encryption for ecto queries
  ECTO_USE_SSL: "false"

  # Fetching coin exchange rates from CoinGecko
  DISABLE_EXCHANGE_RATES: "true"

  # List of supported chains for chain dropdown
  SUPPORTED_CHAINS: []

  # Number of days for fetching of history of txs count for display
  TXS_STATS_DAYS_TO_COMPILE_AT_INIT: 10
  
  # Enable Smart-contract verification microservice
  MICROSERVICE_SC_VERIFIER_ENABLED: "false"
  MICROSERVICE_SC_VERIFIER_URL: http://sc-verifier:8050
  MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier

  # Enable Visualizer services such as SOL2UML
  MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: "false"
  MICROSERVICE_VISUALIZE_SOL2UML_URL: http://visualizer:8050
    
  # Enable Sig-provider which is used to display decoded transaction data on transaction pages and to determine transaction actions.
  MICROSERVICE_SIG_PROVIDER_ENABLED: "false"
  MICROSERVICE_SIG_PROVIDER_URL: http://sig-provider:8050

blockscout_frontend_env_variables:
  # API conf
  NEXT_PUBLIC_API_HOST: "{{ blockscout_frontend_host_name }}"
  NEXT_PUBLIC_API_PROTOCOL: "{{ blockscout_frontend_protocol }}"
  NEXT_PUBLIC_API_BASE_PATH: /
  FAVICON_MASTER_URL: "https://ash.center/img/ash-logo.svg"

  # Network
  NEXT_PUBLIC_NETWORK_NAME: Ash Subnet
  NEXT_PUBLIC_NETWORK_SHORT_NAME: Ash
  NEXT_PUBLIC_NETWORK_ID: 66666
  NEXT_PUBLIC_NETWORK_RPC_URL: "{{ blockscout_rpc }}"

  # Coin
  NEXT_PUBLIC_NETWORK_CURRENCY_NAME: AshCoin
  NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ASH
  NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18

  # App conf
  NEXT_PUBLIC_APP_HOST: "{{ blockscout_frontend_host_name }}"
  NEXT_PUBLIC_APP_PROTOCOL: "{{ blockscout_frontend_protocol }}"

  # Miscellaneous
  NEXT_PUBLIC_HOMEPAGE_CHARTS: ['daily_txs']
  NEXT_PUBLIC_IS_TESTNET: "true"
  NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: "{{ blockscout_frontend_websocket_protocol }}"
  NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml

  # Visualizer
  NEXT_PUBLIC_VISUALIZE_API_HOST: "{{ blockscout_frontend_url }}"
  NEXT_PUBLIC_VISUALIZE_API_BASE_PATH: /visualizer-service

  # Stats
  NEXT_PUBLIC_STATS_API_HOST: "{{ blockscout_frontend_url if blockscout_stats_enabled in ['true', true] else None }}"
  NEXT_PUBLIC_STATS_API_BASE_PATH: /stats-service

  # Other explorers
  # NEXT_PUBLIC_FEATURED_NETWORKS: "{{ [{'title': 'ASH Layer', 'url': blockscout_frontend_url, 'group': 'Testnets', 'icon': 'https://ash.center/img/ash-logo.svg', 'isActive': true}] | to_json }}"

  # Other links
  # NEXT_PUBLIC_OTHER_LINKS: [{'url':'http://10.200.14.212/','text':'Mainnet'}]


blockscout_visualizer_env_variables:
  VISUALIZER__SERVER__GRPC__ENABLED: "false"

blockscout_sig_provider_env_variables:
  SIG_PROVIDER__SERVER__GRPC__ENABLED: "false"

blockscout_sc_verifier_env_variables:
  SMART_CONTRACT_VERIFIER__SERVER__GRPC__ENABLED: "false"

blockscout_stats_env_variables:
  STATS__DB_URL: "{{ blockscout_backend_env_vars.DATABASE_URL | regex_replace('/\\w+?$', '/stats') }}"
  STATS__BLOCKSCOUT_DB_URL: "{{ blockscout_backend_env_vars.DATABASE_URL }}"
  STATS__CREATE_DATABASE: "true"
  STATS__RUN_MIGRATIONS: "true"
  STATS__BLOCKSCOUT_API_URL: "http://backend:4000"
  RUST_BACKTRACE: 1
  STATS__CHARTS_CONFIG: "config/charts.json"
  STATS__LAYOUT_CONFIG: "config/layout.json"
  STATS__UPDATE_GROUPS_CONFIG: "config/update_groups.json"
  STATS__DISABLE_INTERNAL_TRANSACTIONS: "{{ blockscout_backend_env_vars.INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER }}"
  # Only once, after the first start, the stats service will update the stats for all stats
  # STATS__FORCE_UPDATE_ON_START: "true"
